[package]
name = "skill-forge"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/muzin00/skill-forge"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
dotenvy = "0.15"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
serde_json = "1"
wasmtime = "27"
wasmtime-wasi = "27"

[build-dependencies]
wasmtime = "27"

[profile.release]
strip = "symbols"
lto = true
codegen-units = 1
opt-level = "z"
